import deploymentJson from "@deployment";
import {
  createPublicClient,
  createWalletClient,
  custom,
  defineChain,
  erc20Abi,
  formatUnits,
  http,
  parseUnits,
  type Abi,
  type Address,
  type EIP1193Provider,
  type Hash,
} from "viem";

/**
 * Everything on-chain comes from back/deployment.json, which is generated by
 * the Foundry project's deploy script. Nothing here may hardcode an address,
 * chain id, RPC url or ABI - redeploying the contract must not require editing
 * this file.
 */
export interface Deployment {
  contractName: string;
  address: Address;
  chainId: number;
  network: string;
  rpcUrl: string;
  explorerUrl: string;
  deployTxHash: string | null;
  deployedAt: string;
  usdc: { address: Address; symbol: string; decimals: number };
  abi: Abi;
}

export const deployment = deploymentJson as unknown as Deployment;

export const TIMESTREAM_ADDRESS = deployment.address;
export const TIME_STREAM_ABI = deployment.abi;
export const USDC = deployment.usdc;
export const CHAIN_ID = deployment.chainId;

/** Explorer base, derived from the generated per-address explorerUrl. */
export const EXPLORER_BASE = deployment.explorerUrl.replace(/\/address\/.*$/, "");

export const txUrl = (hash: Hash) => `${EXPLORER_BASE}/tx/${hash}`;
export const addressUrl = (address: Address) => `${EXPLORER_BASE}/address/${address}`;

/**
 * The token is NOT hardcoded in the contract: createStream() takes a token
 * argument per stream. Monad testnet USDC is read from the deployment record.
 */
export const USDC_ADDRESS = USDC.address;
export const USDC_DECIMALS = USDC.decimals;

export const toTokenAmount = (value: string): bigint => parseUnits(value, USDC_DECIMALS);
export const fromTokenAmount = (value: bigint): string => formatUnits(value, USDC_DECIMALS);

export const monadTestnet = defineChain({
  id: CHAIN_ID,
  name: "Monad Testnet",
  nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 },
  rpcUrls: { default: { http: [deployment.rpcUrl] } },
  blockExplorers: { default: { name: "MonadScan", url: EXPLORER_BASE } },
  testnet: true,
});

export const publicClient = createPublicClient({
  chain: monadTestnet,
  // The public Monad testnet RPC rejects bursts over 15 requests/second, so reads
  // are batched into few HTTP calls and retried with backoff instead of
  // failing the dashboard on a transient -32011.
  transport: http(deployment.rpcUrl, {
    batch: { wait: 40, batchSize: 20 },
    retryCount: 4,
    retryDelay: 600,
  }),
});

/** The injected provider the app already talks to directly in Home.tsx. */
export function getInjectedProvider(): EIP1193Provider | undefined {
  const ethereum = (
    window as Window & { ethereum?: EIP1193Provider }
  ).ethereum;
  return ethereum ?? undefined;
}

export function getWalletClient(provider: EIP1193Provider) {
  return createWalletClient({ chain: monadTestnet, transport: custom(provider) });
}

// ---------------------------------------------------------------------------
// Network handling
// ---------------------------------------------------------------------------

const CHAIN_ID_HEX = `0x${CHAIN_ID.toString(16)}`;

/**
 * Ensure the wallet is on Monad testnet, adding the network if the wallet does
 * not know it yet. Returns the chain id the wallet ends up on, so the caller
 * can surface a clear error instead of sending a tx to the wrong chain.
 */
export async function ensureMonadNetwork(provider: EIP1193Provider): Promise<number> {
  const current = Number(
    await provider.request({ method: "eth_chainId" }),
  ) as number;

  if (current === CHAIN_ID) return CHAIN_ID;

  try {
    await provider.request({
      method: "wallet_switchEthereumChain",
      params: [{ chainId: CHAIN_ID_HEX }],
    });
  } catch (error) {
    // 4902 = the chain is unknown to the wallet, so register it first.
    if ((error as { code?: number }).code !== 4902) throw error;
    await provider.request({
      method: "wallet_addEthereumChain",
      params: [
        {
          chainId: CHAIN_ID_HEX,
          chainName: monadTestnet.name,
          nativeCurrency: monadTestnet.nativeCurrency,
          rpcUrls: [deployment.rpcUrl],
          blockExplorerUrls: [EXPLORER_BASE],
        },
      ],
    });
  }

  const after = Number(
    await provider.request({ method: "eth_chainId" }),
  ) as number;
  if (after !== CHAIN_ID) {
    throw new Error(
      `Wallet is on chain ${after}, expected Monad testnet (${CHAIN_ID}).`,
    );
  }
  return after;
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/** Mirrors the 11-field Stream struct plus the separate duration mapping. */
export interface StreamRecord {
  client: Address;
  freelancer: Address;
  token: Address;
  totalAmount: bigint;
  startTime: bigint;
  endTime: bigint;
  withdrawn: bigint;
  active: boolean;
  accepted: boolean;
  lastCheckIn: bigint;
  checkInInterval: bigint;
  durationSeconds: bigint;
}

export async function readStream(streamId: bigint): Promise<StreamRecord> {
  const [stream, durationSeconds] = await Promise.all([
    publicClient.readContract({
      address: TIMESTREAM_ADDRESS,
      abi: TIME_STREAM_ABI,
      functionName: "getStream",
      args: [streamId],
    }),
    publicClient.readContract({
      address: TIMESTREAM_ADDRESS,
      abi: TIME_STREAM_ABI,
      functionName: "streamDuration",
      args: [streamId],
    }),
  ]);

  const [client, freelancer, token, totalAmount, startTime, endTime, withdrawn, active, accepted, lastCheckIn, checkInInterval] = stream as readonly [
    Address,
    Address,
    Address,
    bigint,
    bigint,
    bigint,
    bigint,
    boolean,
    boolean,
    bigint,
    bigint,
  ];

  return {
    client,
    freelancer,
    token,
    totalAmount,
    startTime,
    endTime,
    withdrawn,
    active,
    accepted,
    lastCheckIn,
    checkInInterval,
    durationSeconds: durationSeconds as bigint,
  };
}

export async function readEarnedAmount(streamId: bigint): Promise<bigint> {
  return publicClient.readContract({
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "earnedAmount",
    args: [streamId],
  }) as Promise<bigint>;
}

export async function readStreamCount(): Promise<bigint> {
  return publicClient.readContract({
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "streamCount",
  }) as Promise<bigint>;
}

export async function readErc20Balance(
  token: Address,
  account: Address,
): Promise<bigint> {
  return publicClient.readContract({
    address: token,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [account],
  }) as Promise<bigint>;
}

export async function readErc20Allowance(
  token: Address,
  owner: Address,
  spender: Address,
): Promise<bigint> {
  return publicClient.readContract({
    address: token,
    abi: erc20Abi,
    functionName: "allowance",
    args: [owner, spender],
  }) as Promise<bigint>;
}

// ---------------------------------------------------------------------------
// Writes
// ---------------------------------------------------------------------------

export type TxStep = "approve" | "createStream" | "acceptStream" | "checkIn" | "withdraw" | "stopStream";

export interface CreateStreamArgs {
  freelancer: Address;
  token: Address;
  totalAmount: bigint;
  durationSeconds: bigint;
  checkInIntervalSeconds: bigint;
}

/** Step 1 of creating a stream: let the contract pull the escrowed amount. */
export async function approveUsdc(
  provider: EIP1193Provider,
  account: Address,
  amount: bigint,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: USDC_ADDRESS,
    abi: erc20Abi,
    functionName: "approve",
    args: [TIMESTREAM_ADDRESS, amount],
  });
}

export async function createStream(
  provider: EIP1193Provider,
  account: Address,
  args: CreateStreamArgs,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "createStream",
    args: [
      args.freelancer,
      args.token,
      args.totalAmount,
      args.durationSeconds,
      args.checkInIntervalSeconds,
    ],
  });
}

export async function acceptStream(
  provider: EIP1193Provider,
  account: Address,
  streamId: bigint,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "acceptStream",
    args: [streamId],
  });
}

/**
 * Only the freelancer may call this. Accrual stops at
 * lastCheckIn + checkInInterval, so a missed check-in silently caps earnings.
 */
export async function checkIn(
  provider: EIP1193Provider,
  account: Address,
  streamId: bigint,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "checkIn",
    args: [streamId],
  });
}

export async function withdraw(
  provider: EIP1193Provider,
  account: Address,
  streamId: bigint,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "withdraw",
    args: [streamId],
  });
}

/** Only the client of that stream may call this. */
export async function stopStream(
  provider: EIP1193Provider,
  account: Address,
  streamId: bigint,
): Promise<Hash> {
  return getWalletClient(provider).writeContract({
    account,
    chain: monadTestnet,
    address: TIMESTREAM_ADDRESS,
    abi: TIME_STREAM_ABI,
    functionName: "stopStream",
    args: [streamId],
  });
}

export async function waitForReceipt(hash: Hash) {
  return publicClient.waitForTransactionReceipt({ hash });
}

/** Turns a viem/contract error into something worth showing a user. */
export function describeError(error: unknown): string {
  if ((error as { code?: number })?.code === 4001) {
    return "Transaction rejected in your wallet.";
  }
  const name = (error as { name?: string })?.name;
  if (name === "ContractFunctionExecutionError" || name === "ContractFunctionRevertedError") {
    const short = (error as { shortMessage?: string })?.shortMessage;
    if (short) return short.replace(/^Error: /, "");
  }
  const message = (error as { shortMessage?: string; message?: string })?.shortMessage
    ?? (error as { message?: string })?.message;
  return message ?? "Unknown error";
}
